language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
    - packages/library/node_modules
    - packages/builder/node_modules
install:
  - npm install
  - npm run bootstrap
script:
  - (cd packages/library && npm run build:starterkit)
  - (cd packages/builder && npm run build)
  - (cd packages/builder && npm run test)
