language: node_js
dist: trusty
sudo: required
addons:
  chrome: stable
  sauce_connect: true
node_js:
  - "node"
git:
  depth: 10
cache:
  directories:
    - node_modules
    - $HOME/.npm
install:
  - npm install
  - npm run bootstrap:ci
script:
  - (cd packages/library && npm run build:starterkit)
  - (cd packages/library && npm test)
  - (cd packages/library && npm run test:sauce)
  - (cd packages/builder && npm run build)
  - (cd packages/builder && npm test)
after_success:
  - (cd packages/builder && npm run deploy)
